---
title: "ClanWarLeagueAttackWarlog"
format: html
editor: visual
---

## Clan War League Attack Warlog

```{r}
## clan tag and api key 

clan_tag = "2RLRCCJ28"

api_key = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImQ4MGU0NDk5LTQ4NGQtNDk1Ni04NDA5LTJmMTQ0YTE3OWJiNiIsImlhdCI6MTczMzQzNTczNCwic3ViIjoiZGV2ZWxvcGVyLzdiNDVjNjFkLWVlNDItMzcyNi02OWY0LTY4YzA5ZjEwNzQ3NCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY5LjYuMTAxLjE4MiJdLCJ0eXBlIjoiY2xpZW50In1dfQ.bVbDt6GhceCIfeBP4bR-reBYXN6hUuGMfM8FHyYqLgfVOuCJF85vvHGhkBY04Q2t3aP_sadep3VlKdX8B3ylcQ"
```

```{r}
## get response.

league_url <- paste("https://api.clashofclans.com/v1/clans/%23", clan_tag ,"/currentwar/leaguegroup", sep = "")

# Make the GET request
league_response <- GET(
  league_url,
  add_headers(
    Authorization = paste("Bearer", api_key)
  )
)


# Check if the request was successful
if (status_code(league_response) == 200) {
  # Parse the JSON content
  league_data <- content(league_response, as = "text")
  league_parsed_data<- fromJSON(league_data, flatten = TRUE)
  
} else {
  print(paste("Failed to fetch data. Status code:", status_code(league_response)))
}


```

```{r}
## instead of getting only wars the desired clan is in, get every war so we can keep track of clans we havent faught yet

tags <- league_parsed_data$rounds[[1]]
all_tags <- unlist(tags)
all_tags <- gsub("#", "%23", all_tags)



#####################

desired_clan_tag <- "#2RLRCCJ28"  
matching_war_tags <- list()

# Loop through each war tag
for (warTag in all_tags) {
    # Construct the URL with the encoded war tag
    url_loop2 <- paste0("https://api.clashofclans.com/v1/clanwarleagues/wars/", warTag)

    # Make the API request
    war_data <- httr::GET(url_loop2, add_headers(Authorization = paste("Bearer", api_key)))
    war_info <- httr::content(war_data)

    # Check if the clan is participating in this war
    if (war_info$clan$tag == desired_clan_tag || war_info$opponent$tag == desired_clan_tag) {
        matching_war_tags <- append(matching_war_tags, warTag)
       
    }
}

# Print all matching war tags
if (length(matching_war_tags) > 0) {
} else {
    cat("Clan not found in any of the wars.\n")
}
#################################

matching_war_tags <- unlist(matching_war_tags)
matching_war_tags <- gsub("#", "%23", matching_war_tags)



```

```{r}

#################################

## now need to loop through all of these wars and save the attacks in the same manor we did in clanwarattackswarlog


warLog <- data.frame()

for (warTag in matching_war_tags) {
    # Construct the URL with the encoded war tag
    url_loop3 <- paste0("https://api.clashofclans.com/v1/clanwarleagues/wars/", warTag)
    
    
    

  # Make the GET request
league_response2 <- GET(
  url_loop3,
  add_headers(
    Authorization = paste("Bearer", api_key)
  )
)


# Check if the request was successful
if (status_code(league_response2) == 200) {
  # Parse the JSON content
  league_data2 <- content(league_response2, as = "text")
  league_parsed_data2<- fromJSON(league_data2, flatten = TRUE)
  
} else {
  print(paste("Failed to fetch data. Status code:", status_code(league_response2)))
}
    
    state <-league_parsed_data2$state
    
    if(state != c("notInWar")){
    
  clan <- league_parsed_data2$clan$members
  opp <- league_parsed_data2$opponent$members
  
  
  
  ## create a table of all attacks
  list_att <- list(clan$attacks)
  attacks_table <- bind_rows(list_att)
  
  ## add thlevel and position
  
  if (nrow(attacks_table) > 0){
    
      full_attacks <- left_join(attacks_table, clan, by= join_by(attackerTag == tag))

      full_attacks <- full_attacks %>% select(1:9) %>% left_join(., opp, by = join_by(defenderTag == tag))
  
  
  
      full_attacks <- full_attacks %>% select(1:12)
  
  
      full_attacks <- full_attacks %>% mutate(clanTag = clan_tag, warDate = Sys.Date())
  
       warLog <- rbind(full_attacks, warLog)

  }
  }
  

}

warLog <- unique(warLog)

write.csv(warLog, "LeagueWarLog.csv", quote = FALSE, row.names = FALSE, append            = TRUE)

```
