---
title: "ClanWarAttackWarlog"
format: html
editor: visual
---

```{r}
## load packages
library(httr)
library(jsonlite)
library(dplyr)
library(ggplot2)
library(tidyverse)
```

```{r}
## clan tag and api key 

clan_tag = "2RLRCCJ28"

api_key = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImQ4MGU0NDk5LTQ4NGQtNDk1Ni04NDA5LTJmMTQ0YTE3OWJiNiIsImlhdCI6MTczMzQzNTczNCwic3ViIjoiZGV2ZWxvcGVyLzdiNDVjNjFkLWVlNDItMzcyNi02OWY0LTY4YzA5ZjEwNzQ3NCIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjY5LjYuMTAxLjE4MiJdLCJ0eXBlIjoiY2xpZW50In1dfQ.bVbDt6GhceCIfeBP4bR-reBYXN6hUuGMfM8FHyYqLgfVOuCJF85vvHGhkBY04Q2t3aP_sadep3VlKdX8B3ylcQ"
  

```

```{r}
## get response.

url <- paste("https://api.clashofclans.com/v1/clans/%23", clan_tag ,"/currentwar", sep = "")

# Make the GET request
response <- GET(
  url,
  add_headers(
    Authorization = paste("Bearer", api_key)
  )
)


# Check if the request was successful
if (status_code(response) == 200) {
  # Parse the JSON content
  data <- content(response, as = "text")
  parsed_data<- fromJSON(data, flatten = TRUE)
  
} else {
  print(paste("Failed to fetch data. Status code:", status_code(response)))
}


```

```{r}
# check if in war 
par <- parsed_data$state
currentwar <- read_csv("CurrentWar.csv")


if (par %in% c("inWar", "warEnded")) {
  ## seperate clan members
  clan <- parsed_data$clan$members
  opp <- parsed_data$opponent$members
  
  
  
  ## create a table of all attacks
  list_att <- list(clan$attacks)
  attacks_table <- bind_rows(list_att)
  
  ## add thlevel and position
  full_attacks <- left_join(attacks_table, clan, by= join_by(attackerTag == tag))

  full_attacks <- full_attacks %>% select(1:9) %>% left_join(., opp, by = join_by(defenderTag == tag))
  
  
  
  full_attacks <- full_attacks %>% select(1:12)
  
  
  full_attacks <- full_attacks %>% mutate(clanTag = clan_tag, warDate = Sys.Date())
  


  if (any(currentwar$defenderTag %in% full_attacks$defenderTag)){
      # same war, update dataset.
      write_csv(full_attacks, "CurrentWar.csv")
  
  
  }else {
      # new war, append old set and start new
      write_csv(full_attacks, "WarLog.csv", append = TRUE)
      # clear currentwar
      currentwar <- currentwar[0,]
  
  }
} else {
  print("Currently not in war.")
}






```

# 
